export const PAGES_FETCH = 'PAGES/FETCH';
export const PAGES_LOADING_SHOW = 'PAGES/LOADING/SHOW';
export const PAGES_LOADING_HIDE = 'PAGES/LOADING/HIDE';
export const PAGES_LOADED = 'PAGES/PAGES_LOADED';
export const SET_CURRENT_PAGE = 'PAGES/SET_CURRENT_PAGE';
export const SET_SEARCH_QUERY = 'PAGES/SET_SEARCH_QUERY';

export const SET_LOADING_ROW = 'ROW/SET_LOADING_ROW'